### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by HQ1791** [brandonrobertz/chatgpt-document-extraction#1]
Hi,
I am trying to input a json file and output in another json file. But i am getting a foolowing error.
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2095822: character maps to <undefined>`

I have a json file from graph database. It contain URIs. Can you tell me how can i  get rid of this issue?

Thanks!

**Comment by HQ1791** [comment]
Okay i get rid of above error by putting `error="ignore"`
Now i am getting another kind of error, when i execute the below command:

`$ ./gpt-extract.py --input-type json ~/Desktop/Archive/statements.json --keydoc @graph  outfile ~/Desktop/Archive/output.json
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\chatgpt-document-extraction\gpt-extract.py", line 262, in <module>
    with open(args.schema_file, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'outfile'`

Can you please provide an example of how it works?

Thanks!

**Comment by brandonrobertz** [comment]
The usage of arguments above isn't quite right. `./gpt-extract.py --help` gives all the arguments in the order they're supposed to be in. "outfile" should be the output file path. Also it also looks like you're missing the JSON schema file. To fix your usage, try something like this:

`./gpt-extract.py --input-type json --keydoc @graph ~/Desktop/Archive/statements.json ~/Desktop/Archive/SCHEMA-FILE-HERE.JSON ~/Desktop/Archive/output.json`

You'll need to create a JSON schema (saved as `SCHEMA-FILE-HERE.JSON` using the above usage example) describing the output format you want ChatGPT to try to use. An example JSON schema is here:

```
{
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "descriptive name of field here": { "type": "data type here" },
      }
}
```

You can read more about JSON schema here: https://json-schema.org/

Full arguments are:
`gpt-extract.py [-h] [--input-type {txt,json}] [--keydoc KEYDOC] [--keyid KEYID] [--headless] [--continue-at CONTINUE_AT] [--continue-last]  infile schema_file outfile`

I'll add some better examples and stuff to the documentation. In the meantime, I have a little more detail about the process here: https://source.opennews.org/articles/testing-pdf-data-extraction-chatgpt/

**Comment by HQ1791** [comment]
Thankyou for the quick response. I have json input file that looks like this:
`[ {
  "@graph" : [ {
    "@id" : "http://gk50.geolba.ac.at/feat/1",
    "http://gk50.geolba.ac.at/hasUnit" : [ {
      "@id" : "http://gk50.geolba.ac.at/unit/8159"
    } ]
  }, {
    "@id" : "http://gk50.geolba.ac.at/feat/10",
    "http://gk50.geolba.ac.at/hasUnit" : [ {
      "@id" : "http://gk50.geolba.ac.at/unit/9"
    } ]`

and I have json schema file that looks like this:
`{
      "type": "object",
      "properties": {
        "@graph": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "@id": {
                  "type": "string"
                },
                "http://gk50.geolba.ac.at/hasUnit": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "@id": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    }`
When i execute the following command:
`$ ./gpt-extract.py --input-type json --keydoc @graph ~/Desktop/Archive/statements.json ~/Desktop/Archive/schema.json ~/Desktop/Archive/output.json`
I see it start the ChatGPT interface but after some seconds it throws this error:
`Traceback (most recent call last):
  File "C:\Users\admin\Desktop\chatgpt-document-extraction\gpt-extract.py", line 269, in <module>
    run(documents, schema, args.outfile,
  File "C:\Users\admin\Desktop\chatgpt-document-extraction\gpt-extract.py", line 167, in run
    results = json.load(f)
              ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
Its causing issue with json file.

**Comment by brandonrobertz** [comment]
That error is saying your `output.json` isn't proper JSON. Make sure the file is a proper JSON formatted file, or remove it entirely. The script will attempt to load the output file and continue where it left off and if the output JSON file is corrupt, the script will fail.

**Comment by HQ1791** [comment]
The `output.json` was empty from start . I removed the output file and then i get this error.

`$ ./gpt-extract.py --input-type json --keydoc @graph ~/Desktop/Archive/statements.json ~/Desktop/Archive/schema.json ~/Desktop/Archive/output.json
`
Then chatgpt get started and this time shows little more execution:
`
Starting ChatGPT interface...
5 documents to scrape
Doc ID: 0 Text length: 15630
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\chatgpt-document-extraction\gpt-extract.py", line 269, in <module>
    run(documents, schema, args.outfile,
  File "C:\Users\admin\Desktop\chatgpt-document-extraction\gpt-extract.py", line 200, in run
    prompt, response = scrape_via_prompt(chat, page_text, schema)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\chatgpt-document-extraction\gpt-extract.py", line 87, in scrape_via_prompt
    prompt = f"```{clean_document(page_text)}```\n\nFor the given text, can you provide a JSON representation that strictly follows this schema:\n\n```{schema}```"
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\chatgpt-document-extraction\gpt-extract.py", line 78, in clean_document
    cleaned = re.sub(r"[\t ]+", " ", re.sub(r"[\n]+", "\n", page_text)).strip()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'list'
`

What exactly should be inside in  `output.json` file?

**Comment by HQ1791** [comment]
Okay I have made it worked by changing list to string
`cleaned = re.sub("[\n]+", "\n", re.sub("[ \t]+", " ", page_text)).strip()
`
to

`cleaned = re.sub(r"[\t ]+", " ", re.sub(r"[\n]+", "\n", str(page_text))).strip()`

I can see output in chatgpt now. 
Thankyou!

**Comment by brandonrobertz** [comment]
It looks like your documents are actually lists? The script assumes your keydoc points to a string, not any other data type. E.g., if your input data is:

```
[{
  "id": 1
  "doc": "My text here..."
}, {
  "id": 2,
  "doc": "Another record..."
}]
```

Your `--keydoc` should be "doc". It looks like your `@graph` key might point to a list.

Glad you got this working! I'll add some documentation around all this.
